services:
 postgres:
    image: postgis/postgis:latest
    ports:
      - "5432:5432"
    container_name: postgres-news
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

 redis:
   image: redis:7.2.3-alpine
   container_name: redis
   hostname: localhost
   restart: always
   ports:
     - "6379:6379"